services:
  postgres:
    image: postgres:17.2
    container_name: postgres-test
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: wallet
